### ISSUE TITLE
Issue with docker build in v0.0.2rc6

### ISSUE THREAD

**Issue by C-Achard** [conda-forge/napari-cellseg3d-feedstock#7]
### Comment:

Hello @goanpeca @jaimergp, I've been trying to fix errors in the Azure pipeline docker build step in #6 to update my package's feedstock and I was wondering if you could help.

Please find the log [here ](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=694035&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d) : it seems to be an issue with importlib.metadata.metadata(app_module)
stating that a distribution name is required when importing napari in the plugin's code ([line 1173 of the log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=694035&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1173)).

When I run importlib.metadata.metadata('napari-cellseg3d') locally I get the following :
```
 {'Metadata-Version': '2.1',
 'Name': 'napari-cellseg3d',
 'Version': '0.0.2rc6',
 'Summary': 'plugin for cell segmentation',
 'Home-page': 'https://github.com/AdaptiveMotorControlLab/CellSeg3d',
 'Author': 'Cyril Achard, Maxime Vidal, Jessy Lauer, Mackenzie Mathis',
 'Author-email': 'cyril.achard@epfl.ch, maxime.vidal@epfl.ch, mackenzie@post.harvard.edu',
 'License': 'MIT',
 'Project-URL': 'Bug Tracker, https://github.com/AdaptiveMotorControlLab/CellSeg3d/issues',
 'Classifier': 'Development Status :: 2 - Pre-Alpha',
 'Requires-Python': '>=3.8',
 'Description-Content-Type': 'text/markdown',
 'License-File': 'LICENSE',
 'Requires-Dist': 'numpy'}
```
Am I missing a field in recipe/meta.yaml or in my plugin's pyproject.toml ? Thank you kindly for your aid

Main package repo : https://github.com/AdaptiveMotorControlLab/CellSeg3d (see release v0.0.2rc6)

**Comment by jaimergp** [comment]
Hey @C-Achard, I think this is a problem with Py 3.11. Check https://github.com/conda-forge/napari-feedstock/issues/45. Once that one is fixed, you won't see errors here. Let's just wait a bit for now 🤞
